### ISSUE TITLE
vjoy is not enabling v2.1.8

### ISSUE THREAD

**Issue by sharukhrahman97** [TanayKarve/Driving-using-motion-recogniton#1]
I have installed vjoy and whenever I install vjoy it fails. by visiting the log I came up with this "[E]  AssignCompatibleId: Function CM_Get_Child failed with error: 0000000D". when I try to open vjoy feeder demo I found this"Failed
vJoy Driver (version 0000) does not match vJoyInterface DLL (version 0218)". please help me.

**Comment by TanayKarve** [comment]
This is usually the case when DLL file vJoyInterface.dll fails to communicate properly with the driver. Either the versions mismatch or the driver is not properly installed or a bug in either.
I'd start by uninstalling everything, re-installing vJoy  and testing it with vJoyFeeder. If this does not work then there might be a major problem.

**Comment by sharukhrahman97** [comment]
Yeah, i did what you said but still the problem exists. I have contacted
the developer of vjoy he said that the problem has not been solved yet.

Thank you for your reply, love your project BTW.

**Comment by TanayKarve** [comment]
Thanks a lot, closing this issue.
Feel free to open for further issues.
